@echo off
echo Firma Yonetim Uygulamasi baslatiliyor...
echo.
echo 1. Vite dev server baslatiliyor...
start "Vite Dev Server" cmd /k "npm run dev"
echo.
echo 2. 3 saniye bekleniyor...
timeout /t 3 /nobreak >nul
echo.
echo 3. Electron uygulamasi baslatiliyor...
npm run electron
echo.
echo Uygulama kapatildi. Herhangi bir tusa basin...
pause >nul
